# Generated by Django 4.1.2 on 2022-10-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makgeolli', '0001_initial'),
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='makgeolli.makgeolli'),
        ),
    ]
