# Generated by Django 4.1.2 on 2022-10-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makgeolli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cobby/')),
                ('name', models.CharField(max_length=1)),
            ],
        ),
    ]
